Fix bug with search index on Django 2.2.1
After upgrading to Django 2.2 I got an error when posting a new
annotation:

```
django.core.exceptions.FieldError: Cannot resolve expression type, unknown output_field
```

Which was happening with this in
`pepysdiary.common.signals.make_updater()`:

```
search_vectors.append(
    SearchVector(Value(text, output_field=TextField()), weight=weight)
)
```

Googling, it seems to be [a bug in Django 2.2](https://code.djangoproject.com/ticket/30446)

Fixed it as suggested there, and the same way that Simon Willison
did in https://github.com/simonw/simonwillisonblog/pull/25