Fix error in Django 4.1 when rendering an email template
Was getting errors like this:

```
======================================================================
ERROR: test_create_inactive_user (tests.membership.test_managers.PersonManagerTestCase)
It should create an inactive user
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/code/tests/membership/test_managers.py", line 81, in test_create_inactive_user
    Person.objects.create_inactive_user(
  File "/code/pepysdiary/membership/managers.py", line 73, in create_inactive_user
    person.send_activation_email(site)
  File "/code/pepysdiary/membership/models.py", line 194, in send_activation_email
    email_user(
  File "/code/pepysdiary/membership/utilities.py", line 89, in email_user
    return email_list([user.email], template_path, from_address, context_dict)
  File "/code/pepysdiary/membership/utilities.py", line 65, in email_list
    nodes = dict(
  File "/code/pepysdiary/membership/utilities.py", line 65, in <genexpr>
    nodes = dict(
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 158, in __iter__
    yield from node
TypeError: 'BlockNode' object is not iterable
```

But eventually found that using `loader.get_template(template_path).template.nodelist`
instead of `loader.get_template(template_path).template` did the
job when getting all the `BlockNode`s to iterate through.