Add pinned version of coverage
Was getting these errors when running coveralls:

    ImportError: cannot import name 'Reporter' from 'coverage.report' 

    TypeError: __init__() missing 1 required positional argument: 'name'

Which I think is because coverage 6.x has changed and coveralls has problems with it. So, specifically adding coverage < 6.